# Standard
runtime: python39

# pick one of the following blocks
# <
instance_class: F4
# >
# -or-
# <
#instance_class: B8
#basic_scaling:
#  max_instances: 10
#  idle_timeout: 30m
# >

entrypoint: gunicorn -b :$PORT main:app

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 1d

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
