# Important: If you modify this file, you may also need to modify terraform/core/main.tf.

# Standard
runtime: python39

# pick one of the following blocks
# <
instance_class: F4
# >
# -or-
# <
#instance_class: B8
#basic_scaling:
#  max_instances: 10
#  idle_timeout: 30m
# >

entrypoint: gunicorn -b :$PORT app_engine:app

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 0s

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 0s

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

includes:
  - env_variables.yaml
