name: 'Terraform Development'

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Key
      working-directory: server
      run: echo "$SERVICE_KEY" > key.json'
      shell: bash
      env:
        SERVICE_KEY: ${{secrets.SERVICE_KEY}}
        
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: terraform/dev
      run: terraform init -var project_id=${{sercrets.PROJECT_ID}} -var project_url=${{secrets.PROJECT_URL}}

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: terraform/dev
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      working-directory: terraform/dev
      run: terraform plan -var project_id=${{sercrets.PROJECT_ID}} -var project_url=${{secrets.PROJECT_URL}}

      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -var project_id=${{sercrets.PROJECT_ID}} -var project_url=${{secrets.PROJECT_URL}} -auto-approve
